//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEl
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_BaseGeography
    {
        public SYS_BaseGeography()
        {
            this.User = new HashSet<User>();
            this.User1 = new HashSet<User>();
            this.User2 = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string GeographySN { get; set; }
        public Nullable<int> GeographyLevel { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ParentSN { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> IsValid { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual ICollection<User> User2 { get; set; }
    }
}
