//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEl
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string LoginName { get; set; }
        public string PassWord { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool IsValid { get; set; }
    
        public virtual SYS_BaseGeography SYS_BaseGeography { get; set; }
        public virtual SYS_BaseGeography SYS_BaseGeography1 { get; set; }
        public virtual SYS_BaseGeography SYS_BaseGeography2 { get; set; }
        public virtual SYS_UserRole SYS_UserRole { get; set; }
    }
}
