//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZSEntities : DbContext
    {
        public ZSEntities()
            : base("name=ZSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class> Class { get; set; }
        public DbSet<LongUrlToShorturl> LongUrlToShorturl { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<SYS_BaseGeography> SYS_BaseGeography { get; set; }
        public DbSet<SYS_ClassLevel> SYS_ClassLevel { get; set; }
        public DbSet<SYS_UserRole> SYS_UserRole { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<User> User { get; set; }
    }
}
